---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - audit_commits
  - collect_commits
  - enqueue_projects
  - initial_audits
  - push_commits
:limits:
  initial_audits: 1
  collect_commits: 3
